[build]
  command = "cd client && npm run build"
  publish = "client/dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  included_files = []
  external_node_modules = ["mongoose", "@google/genai", "cloudinary", "dotenv"]
